# Generated by Django 3.2.6 on 2021-10-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Driver_Password',
        ),
    ]
