# Generated by Django 3.2.6 on 2021-10-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0002_remove_driver_driver_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order_ID',
            new_name='OrderItem_ID',
        ),
    ]
