# Generated by Django 3.2.6 on 2021-10-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0003_rename_order_id_orderitem_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Driver_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodies.driver'),
        ),
    ]
