# Generated by Django 3.2.6 on 2021-10-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0005_orderitem_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Driver_ContactNumber',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
