# Generated by Django 3.2.6 on 2021-10-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0010_alter_order_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Driver_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodies.driver'),
        ),
    ]
