# Generated by Django 3.2.6 on 2021-10-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0011_alter_order_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Restaurant_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodies.restaurant'),
            preserve_default=False,
        ),
    ]
